version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      - POSTGRES_USER:'whoeuuohhmtirt'
      - POSTGRES_PASSWORD:'64b4737e6536f80f29d1d26273419cacf7a2a2869a70d8c4e43914330efbf92b'
      - POSTGRES_DB:'din812vclohoc'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "quest.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/quest'
    ports:
      - '8000:8000'

volumes:
  postgres:
  redis:
